#!/usr/bin/env bash
# Script to loop from 1 to 10 and:
#   Displays "bad luck" for the 4th iteration
#   Displays "good luck" for the 8th iteration
#   Displays "Best School" for all other iterations

c=0

while [ $c -lt 10 ]
do
  if [ $c -eq 3 ]
  then
    echo "bad luck"
  elif [ $c -eq 7 ]
  then
    echo "good luck"
  else
    echo "Best School"
  fi
  (( c++ ))
done
