#!/usr/bin/env bash
# Displays numbers from 1 to 20 in addition to:
#   displays 4 and then bad luck from China for the 4th loop iteration
#   displays 9 and then bad luck from Japan for the 9th loop iteration
#   displays 17 and then bad luck from Italy for the 17th loop iteration

idx=1

while [ $idx -le 20 ]
do
  echo "$idx"
  case $idx in
    "4") echo "bad luck from China";;
    "9") echo "bad luck from Japan";;
    "17") echo "bad luck from Italy";;
  esac
  (( idx++ ))
done
